[package]
name = "resistance_fort"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
lazy_static = "1.5.0"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
